### PR TITLE
update whisper key derivation path

### PR DESCRIPTION
**Pull request by gravityblast**
@corpetty @oskarth does it make sense to update the derivation path in the `Terms Glossary` as well?

### CODE REVIEW

**Comment by decanus** [comment]
I'd say yes

**Review by andremedeiros — APPROVED** [review]

**Comment by gravityblast** [comment]
I don't have permissions to merge, feel free to merge it when you want

**Comment by oskarth** [comment]
@gravityblast Could you elaborate on this change a bit? Was the previous spec wrong? Is this a change? In which version?

@decanus lets not merge so quickly next time :)

**Comment by gravityblast** [comment]
@oskarth yes the spec was wrong. The `Terms Glossary` said that the whisper key uses this derivation path `m/44'/60'/0'/0/0`, which was the one used before the multi-account implementation.
This PR updates that path with the one we are currently using: `m/43'/60'/1581'/0'/0`.

**Pull request merged**
