### PR TITLE
Add link to superscripts

### PR DESCRIPTION
**Pull request by D4nte**
The footnotes section is before the appendix so it
is hard to understand what the superscripts refer to.

### CODE REVIEW

**Comment by jakubgs** [comment]
Is this ready for review? No reviewers were added.

**Comment by D4nte** [comment]
> Is this ready for review? No reviewers were added.

It is ready for review.

**Review by oskarth — COMMENTED** [review]
Seems fine to me, but people involved in day to day of Status app/protocol dev will know better

**Comment by D4nte** [comment]
@cammellos can you please review?

**Review by cammellos — APPROVED** [review]

**Pull request merged**
